# Inserción de base de datos ficticia para el correcto funcionamiento de la aplicación

languages = [
  { id: 1, language: 'Inglés A2'},
  { id: 2, language: 'Inglés B1'},
  { id: 3, language: 'Inglés B2'},
  { id: 4, language: 'Inglés C1'},
  { id: 5, language: 'Inglés C2'},
  { id: 6, language: 'Inglés C3'},
  { id: 7, language: 'Portugués Básico'},
  { id: 8, language: 'Portugués Intermedio'},
  { id: 9, language: 'Portugués Avanzado/Técnico'},
  { id: 10, language: 'Japonés Básico'},
  { id: 11, language: 'Japonés Intermedio'},
  { id: 12, language: 'Japonés Avanzado/Técnico'},
  { id: 13, language: 'Francés Básico'},
  { id: 14, language: 'Francés Intermedio'},
  { id: 15, language: 'Francés Avanzado/Técnico'},
  { id: 16, language: 'Italiano Básico'},
  { id: 17, language: 'Italiano Intermedio'},
  { id: 18, language: 'Italiano Avanzado/Técnico'}
]

countries = [
  { id: 0, name: 'No aplica / No existe' },
  { id: 1, name: 'Alemania' },
  { id: 2, name: 'Argentina' },
  { id: 4, name: 'Austria' },
  { id: 5, name: 'Bolivia' },
  { id: 6, name: 'Brasil' },
  { id: 7, name: 'Canadá' },
  { id: 8, name: 'China' },
  { id: 9, name: 'Colombia' },
  { id: 10, name: 'Costa Rica' },
  { id: 11, name: 'Corea del Sur' },
  { id: 12, name: 'Cuba' },
  { id: 13, name: 'Dinamarca' },
  { id: 14, name: 'Ecuador' },
  { id: 15, name: 'España' },
  { id: 16, name: 'Estados Unidos' },
  { id: 17, name: 'Finlandia' },
  { id: 18, name: 'Francia' },
  { id: 19, name: 'Guatemala' },
  { id: 20, name: 'Holanda' },
  { id: 21, name: 'Inglaterra' },
  { id: 22, name: 'Israel' },
  { id: 23, name: 'Italia' },
  { id: 24, name: 'India' },
  { id: 25, name: 'Japón' },
  { id: 26, name: 'Marruecos' },
  { id: 27, name: 'México' },
  { id: 28, name: 'Nueva Zelanda' },
  { id: 29, name: 'Palestina' },
  { id: 30, name: 'Paraguay' },
  { id: 31, name: 'Perú' },
  { id: 32, name: 'Portugal' },
  { id: 33, name: 'Puerto Rico' },
  { id: 34, name: 'Rusia' },
  { id: 35, name: 'República Dominicana' },
  { id: 36, name: 'Rumania' },
  { id: 37, name: 'Serbia' },
  { id: 38, name: 'Suiza' },
  { id: 39, name: 'Turquía' },
  { id: 40, name: 'Uruguay' },
  { id: 41, name: 'Uzbekistan' },
  { id: 42, name: 'Gales' },
  { id: 43, name: 'Polonia' },
  { id: 44, name: 'Chile' }
]



colleges = [
  { id: 0, name: 'No seleccionado (Rechazado o Modificable)', country_id: 0 },
  { id: 1, name: 'Rheinische Fiedrich-Wilhelms-Universität Bonn', country_id: 1 },
  { id: 2, name: 'Technische Universität Dresden', country_id: 1 },
  { id: 3, name: 'Europa-Universität Flensburg', country_id: 1 },
  { id: 4, name: 'Georg-August-Universität Göttingen', country_id: 1 },
  { id: 5, name: 'Rheinisch-Westfälische Technische Hochschule Aachen', country_id: 1 },
  { id: 6, name: 'Hochschule für Angewandte Wissenschaften Hamburg', country_id: 1 },
  { id: 7, name: 'Universität Hohenheim', country_id: 1 },
  { id: 8, name: 'Universität Konstanz', country_id: 1 },
  { id: 9, name: 'Handelshochschule Leipzig', country_id: 1 },
  { id: 10, name: 'Westsächsische Hochschule Zwickau', country_id: 1 },
  { id: 11, name: 'Universität Siegen', country_id: 1 },
  { id: 12, name: 'Hochschule Osnabrück', country_id: 1 },
  { id: 13, name: 'Hochschule Weihenstephan-Triesdorf', country_id: 1 },
  { id: 14, name: 'Hochschule RheinMain', country_id: 1 },
  { id: 15, name: 'Universität Bayreuth', country_id: 1 },
  { id: 16, name: 'Universität Mannheim', country_id: 1 },
  { id: 17, name: 'Ludwig-Maximilians-Universität München', country_id: 1 },
  { id: 18, name: 'Hochschule Rhein-Waal', country_id: 1 },
  { id: 19, name: 'Rheinland Pfalz', country_id: 1 },
  { id: 20, name: 'Technische Universität Kaiserslautern', country_id: 1 },
  { id: 21, name: 'Technische Universität München', country_id: 1 },
  { id: 22, name: 'Hochschule Geisenheim', country_id: 1 },
  { id: 23, name: 'Hochschule Ruhr West', country_id: 1 },
  { id: 24, name: 'Pädagogische Hochschule Heidelberg', country_id: 1 },
  { id: 25, name: 'Escuela Argentina de Negocios', country_id: 2 },
  { id: 26, name: 'Universidad Nacional de Cuyo', country_id: 2 },
  { id: 27, name: 'Universidad Nacional del Litoral', country_id: 2 },
  { id: 28, name: 'Universidad Nacional del Comahue', country_id: 2 },
  { id: 29, name: 'Universidad Nacional de San Juan', country_id: 2 },
  { id: 30, name: 'Universidad Nacional de Córdoba', country_id: 2 },
  { id: 31, name: 'Universidad Nacional de Tucumán', country_id: 2 },
  { id: 32, name: 'Pontificia Universidad Católica Argentina - Santa María de los Buenos Aires', country_id: 2 },
  { id: 33, name: 'Universidad Nacional de Villa María', country_id: 2 },
  { id: 34, name: 'Universidad Nacional de San Martín', country_id: 2 },
  { id: 35, name: 'Instituto Universitario de Ciencias de la Salud - Fundación Héctor Alejandro Barceló', country_id: 2 },
  { id: 36, name: 'Universidad de Buenos Aires', country_id: 2 },
  { id: 39, name: 'Fachhochschule Kärnten', country_id: 4 },
  { id: 40, name: 'Donau-Universität Krems', country_id: 4 },
  { id: 41, name: 'Universität Innsbruck', country_id: 4 },
  { id: 42, name: 'Universidad San Francisco Xavier de Chuquisaca', country_id: 5 },
  { id: 43, name: 'Universidade Federal da Paraíba', country_id: 6 },
  { id: 44, name: 'Instituto Brasileiro de Mercado de Capitais (IBMEC)', country_id: 6 },
  { id: 45, name: 'Universidade Estadual de Campinas', country_id: 6 },
  { id: 47, name: 'Universidade Federal de Itajubá', country_id: 6 },
  { id: 48, name: 'Universidade Federal do Oeste do Pará', country_id: 6 },
  { id: 49, name: 'Universidade Federal de Santa Catarina', country_id: 6 },
  { id: 50, name: 'Universidade de São Paulo', country_id: 6 },
  { id: 51, name: 'Universidade Federal de Santa Maria', country_id: 6 },
  { id: 52, name: 'Pontíficia Universidade Católica de Sao Paulo', country_id: 6 },
  { id: 53, name: 'Universidade do Estado de Santa Catarina', country_id: 6 },
  { id: 54, name: 'Universidade do Vale do Río Dos Sinos', country_id: 6 },
  { id: 55, name: 'Universidade de Santa Cruz do Sul', country_id: 6 },
  { id: 56, name: 'Universidade Federal de Mato Grosso', country_id: 6 },
  { id: 57, name: 'Universidade Estadual Norte do Paraná', country_id: 6 },
  { id: 58, name: 'Universidade Federal do Rio Grande du Sul', country_id: 6 },
  { id: 59, name: 'Universidade Federal de Minas Gerais', country_id: 6 },
  { id: 60, name: 'Associação Escola da Cidade', country_id: 6 },
  { id: 61, name: 'Universidade Guarulhos', country_id: 6 },
  { id: 62, name: 'Faculdades Integradas do Brasil', country_id: 6 },
  { id: 63, name: 'Universidade do Oeste de Santa Catarina', country_id: 6 },
  { id: 64, name: 'Serviço Nacional de Aprendizagem Comercial', country_id: 6 },
  { id: 65, name: 'Universidade Federal Rural da Amazonia', country_id: 6 },
  { id: 66, name: 'Pontíficia Universidade Católica do Paraná', country_id: 6 },
  { id: 67, name: 'Universidade Sagrado Coração', country_id: 6 },
  { id: 68, name: 'Universidade Federal do Triangulo Mineiro', country_id: 6 },
  { id: 69, name: 'UNIFAFIFE - Centro Universitário', country_id: 6 },
  { id: 70, name: 'Facultade Projeção', country_id: 6 },
  { id: 71, name: 'Universidade Federal de Ciencias da Saúde de Porto Alegre', country_id: 6 },
  { id: 74, name: 'University of Ottawa', country_id: 7 },
  { id: 75, name: 'University of Regina', country_id: 7 },
  { id: 76, name: 'Yanshan University', country_id: 8 },
  { id: 77, name: 'Universidad de Antioquía', country_id: 9 },
  { id: 78, name: 'Universidad de los Andes', country_id: 9 },
  { id: 79, name: 'Universidad Autónoma de Bucaramanga', country_id: 9 },
  { id: 80, name: 'Universidad del Rosario', country_id: 9 },
  { id: 81, name: 'Universidad de Caldas', country_id: 9 },
  { id: 82, name: 'Universidad Nacional de Colombia', country_id: 9 },
  { id: 83, name: 'Universidad Autónoma de Occidente', country_id: 9 },
  { id: 84, name: 'Universidad CES', country_id: 9 },
  { id: 85, name: 'Universidad del Norte', country_id: 9 },
  { id: 87, name: 'Fundación Universitaria Colombo Internacional', country_id: 9 },
  { id: 88, name: 'Universidad de Santander', country_id: 9 },
  { id: 89, name: 'Fundación Universitaria María Cano', country_id: 9 },
  { id: 90, name: 'Universidad Autónoma de Manizales', country_id: 9 },
  { id: 91, name: 'Universidad de San Buenaventura de Cartagena', country_id: 9 },
  { id: 92, name: 'Universidad Tecnológica de Pereira', country_id: 9 },
  { id: 93, name: 'Universidad de la Costa', country_id: 9 },
  { id: 94, name: 'Universidad Externado de Colombia', country_id: 9 },
  { id: 95, name: 'Universidad Santo Tomás', country_id: 9 },
  { id: 96, name: 'Pontificia Universidad Javeriana', country_id: 9 },
  { id: 97, name: 'Universitaria Agustiniana', country_id: 9 },
  { id: 98, name: 'Fundación Universitaria Konrad Lorenz', country_id: 9 },
  { id: 99, name: 'INCAE Business School', country_id: 10 },
  { id: 100, name: 'Universidad Nacional de Costa Rica', country_id: 10 },
  { id: 101, name: 'Instituto Interamericano de Derechos Humanos', country_id: 10 },
  { id: 102, name: 'Universidad de Costa Rica', country_id: 10 },
  { id: 103, name: 'Corte Interamericana de Derechos Humanos', country_id: 10 },
  { id: 104, name: 'Sungkyunkwan University', country_id: 11 },
  { id: 105, name: 'Incheon National University', country_id: 11 },
  { id: 106, name: 'Kyonggi University', country_id: 11 },
  { id: 107, name: 'Dankook University', country_id: 11 },
  { id: 108, name: 'Universidad de Matanzas Camilo Cienfuegos', country_id: 12 },
  { id: 109, name: 'Aalborg University', country_id: 13 },
  { id: 110, name: 'Universidad Católica de Santiago de Guayaquil', country_id: 14 },
  { id: 111, name: 'Universidad Técnica Estatal de Quevedo', country_id: 14 },
  { id: 112, name: 'Universidad Técnica del Norte de Ibarra', country_id: 14 },
  { id: 113, name: 'Universidad Andina Simón Bolívar', country_id: 14 },
  { id: 114, name: 'Universidad Católica de Cuenca', country_id: 14 },
  { id: 115, name: 'Universidad Regional Amazónica', country_id: 14 },
  { id: 116, name: 'Universidad de Alcalá', country_id: 15 },
  { id: 117, name: 'Universitat de València', country_id: 15 },
  { id: 118, name: 'Universidad de la Laguna', country_id: 15 },
  { id: 119, name: 'Universitat Pompeu Fabra', country_id: 15 },
  { id: 120, name: 'Universidade de Santiago de Compostela', country_id: 15 },
  { id: 121, name: 'Universidad de Deusto', country_id: 15 },
  { id: 122, name: 'Universidade de Vigo', country_id: 15 },
  { id: 123, name: 'Universidad de Málaga', country_id: 15 },
  { id: 124, name: 'Universidad de Granada', country_id: 15 },
  { id: 125, name: 'Universidad de Jaén', country_id: 15 },
  { id: 126, name: 'Universidad Complutense de Madrid', country_id: 15 },
  { id: 127, name: 'Universidad de la Rioja', country_id: 15 },
  { id: 128, name: 'Universidad Pública de Navarra', country_id: 15 },
  { id: 129, name: 'Universitat de Girona', country_id: 15 },
  { id: 130, name: 'Universidad de Valladolid', country_id: 15 },
  { id: 132, name: 'Universidade da Coruña', country_id: 15 },
  { id: 133, name: 'Universidad del País Vasco', country_id: 15 },
  { id: 134, name: 'Universidad de Las Palmas de Gran Canaria', country_id: 15 },
  { id: 135, name: 'Escola Politécnica Superior d Edificació de Barcelona', country_id: 15 },
  { id: 136, name: 'Centro de Investigación Cardiovascular', country_id: 15 },
  { id: 137, name: 'Universidad de Oviedo', country_id: 15 },
  { id: 138, name: 'Universitat Politècnica de València', country_id: 15 },
  { id: 139, name: 'Universidad de Almería', country_id: 15 },
  { id: 140, name: 'Universidad de Zaragoza', country_id: 15 },
  { id: 141, name: 'Universidad Politécnica de Madrid', country_id: 15 },
  { id: 142, name: 'Universitat de Lleida', country_id: 15 },
  { id: 143, name: 'Universidad Miguel Hernández de Elche', country_id: 15 },
  { id: 144, name: 'Universidad de Castilla-La Mancha', country_id: 15 },
  { id: 145, name: 'Universitat Rovira i Virgili', country_id: 15 },
  { id: 146, name: 'Universidad Nacional de Educación a Distancia', country_id: 15 },
  { id: 147, name: 'Universidad de Alicante', country_id: 15 },
  { id: 148, name: 'Universidad Pontificia de Salamanca', country_id: 15 },
  { id: 149, name: 'Universidad de Murcia', country_id: 15 },
  { id: 150, name: 'Universidad de Sevilla', country_id: 15 },
  { id: 151, name: 'Escuela Andaluza de Salud Pública', country_id: 15 },
  { id: 152, name: 'Institut de Teràpia Regenerativa Tissular', country_id: 15 },
  { id: 153, name: 'Universitat de Barcelona', country_id: 15 },
  { id: 154, name: 'University of Connecticut', country_id: 16 },
  { id: 155, name: 'Cornell University', country_id: 16 },
  { id: 156, name: 'Southwest Minnesota State University', country_id: 16 },
  { id: 157, name: 'University of Texas Rio Grande Valley', country_id: 16 },
  { id: 158, name: 'University of California, Davis', country_id: 16 },
  { id: 159, name: 'University of Florida', country_id: 16 },
  { id: 160, name: 'University of Kentucky', country_id: 16 },
  { id: 161, name: 'The University of Arizona', country_id: 16 },
  { id: 162, name: 'Western Carolina University', country_id: 16 },
  { id: 163, name: 'Abo Akademi University', country_id: 17 },
  { id: 164, name: 'Oulu University of Applied Sciences', country_id: 17 },
  { id: 165, name: 'Institut National des Sciences Appliquées Centre Val de Loire', country_id: 18 },
  { id: 166, name: 'Centro Internacional de Estudios Superiores en Ciencias Agronómicas Montpellier SupAgro', country_id: 18 },
  { id: 167, name: 'Federation des Ecoles superieures D ingenieurs en Agriculture', country_id: 18 },
  { id: 168, name: 'Université d Avignon', country_id: 18 },
  { id: 169, name: 'Montpellier Business School', country_id: 18 },
  { id: 170, name: 'Université de Bourgogne', country_id: 18 },
  { id: 171, name: 'Université de Toulon', country_id: 18 },
  { id: 172, name: 'Agrocampus Ouest', country_id: 18 },
  { id: 173, name: 'CFPPA de Beaune', country_id: 18 },
  { id: 174, name: 'École Normale Supérieure de Cachan', country_id: 18 },
  { id: 175, name: 'Université de Bordeaux', country_id: 18 },
  { id: 176, name: 'Institut Universitaire de Technologie de Montpellier', country_id: 18 },
  { id: 177, name: 'Université d Artois', country_id: 18 },
  { id: 178, name: 'École de Hautes Etudes en Commerce International', country_id: 18 },
  { id: 179, name: 'Universidad San Carlos de Guatemala Tricentenaria', country_id: 19 },
  { id: 180, name: 'Erasmus University Rotterdam', country_id: 20 },
  { id: 181, name: 'Hogeschool van Amsterdam', country_id: 20 },
  { id: 182, name: 'Universiteit Twente', country_id: 20 },
  { id: 183, name: 'Universiteit Wageningen', country_id: 20 },
  { id: 184, name: 'University of Warwick', country_id: 21 },
  { id: 185, name: 'University of Nottingham', country_id: 21 },
  { id: 186, name: 'Bezalez Academy of Arts and Design', country_id: 22 },
  { id: 187, name: 'Università degli Studi Roma Tre', country_id: 23 },
  { id: 188, name: 'Università degli Studi di Genova', country_id: 23 },
  { id: 189, name: 'Università della Calabria', country_id: 23 },
  { id: 190, name: 'Università Ca Foscari Venezia', country_id: 23 },
  { id: 191, name: 'SRM University', country_id: 24 },
  { id: 192, name: 'MS Swaminathan Research Foundation', country_id: 24 },
  { id: 193, name: 'Yamagata University', country_id: 25 },
  { id: 194, name: 'ESCA School of Management Casablanca', country_id: 26 },
  { id: 195, name: 'Universidad Autónoma Chapingo', country_id: 27 },
  { id: 196, name: 'Universidad Autónoma Metropolitana', country_id: 27 },
  { id: 197, name: 'Colegio de Postgraduados en Ciencias Agrícolas', country_id: 27 },
  { id: 198, name: 'Universidad de Colima', country_id: 27 },
  { id: 199, name: 'Universidad Autónoma de Chihuahua', country_id: 27 },
  { id: 200, name: 'Universidad de Guadalajara', country_id: 27 },
  { id: 201, name: 'Tecnológico de Monterrey', country_id: 27 },
  { id: 202, name: 'Universidad Vasco de Quiroga', country_id: 27 },
  { id: 203, name: 'Universidad de Monterrey', country_id: 27 },
  { id: 204, name: 'Universidad Autónoma de Nuevo León', country_id: 27 },
  { id: 205, name: 'Instituto Mexicano de Tecnología del Agua', country_id: 27 },
  { id: 206, name: 'Centro de Investigación Científica Yucatán CICY', country_id: 27 },
  { id: 208, name: 'University of Waikato', country_id: 28 },
  { id: 209, name: 'University of Auckland', country_id: 28 },
  { id: 210, name: 'Bethlehem University', country_id: 29 },
  { id: 211, name: 'Universidad Nacional de Asunción', country_id: 30 },
  { id: 212, name: 'Universidad Nacional de Villarrica del Espíritu Santo', country_id: 30 },
  { id: 213, name: 'Ministerio de Salud Pública y Bienestar Social', country_id: 30 },
  { id: 214, name: 'Universidad Católica Santo Toribio de Mogrovejo', country_id: 31 },
  { id: 215, name: 'Universidad Privada Norbert Wiener', country_id: 31 },
  { id: 216, name: 'Universidad Nacional Santiago Antúnez de Mayolo', country_id: 31 },
  { id: 217, name: 'Universidad de Lima', country_id: 31 },
  { id: 218, name: 'Universidade de Aveiro', country_id: 32 },
  { id: 219, name: 'Instituto Politécnico de Setúbal', country_id: 32 },
  { id: 220, name: 'Universidade do Algarve', country_id: 32 },
  { id: 221, name: 'Asociación Interamericana de Contabilidad', country_id: 33 },
  { id: 222, name: 'Universidad Politécnica de Puerto Rico', country_id: 33 },
  { id: 223, name: 'Ural Federal University', country_id: 34 },
  { id: 224, name: 'Instituto Tecnológico de Santo Domingo', country_id: 35 },
  { id: 225, name: 'Instituto Nacional de Recursos Hidráulicos', country_id: 35 },
  { id: 226, name: 'Universitatea Alexandru Ioan Cuza', country_id: 36 },
  { id: 227, name: 'University of Belgrade', country_id: 37 },
  { id: 228, name: 'Zürcher Hochschule für Angewandte Wissenschaften', country_id: 38 },
  { id: 229, name: 'Bezmialem Vakif University', country_id: 39 },
  { id: 230, name: 'Universidad Católica del Uruguay', country_id: 40 },
  { id: 231, name: 'Universidad de la República', country_id: 40 },
  { id: 232, name: 'Pädagogische Hochschule Freiburg', country_id: 1 },
  { id: 233, name: 'Universidade Estadual Paulista', country_id: 6 },
  { id: 234, name: 'Universidade Evangélica - Centro Universitário de Anápolis', country_id: 6 },
  { id: 235, name: 'Korea University - Sejong Campus', country_id: 11 },
  { id: 236, name: 'Universitat Autònoma de Barcelona', country_id: 15 },
  { id: 237, name: 'Universidad de Salamanca', country_id: 15 },
  { id: 239, name: 'Washington State University', country_id: 16 },
  { id: 240, name: 'Burgundy School of Business', country_id: 18 },
  { id: 241, name: 'Université de Rennes 1', country_id: 18 },
  { id: 242, name: 'Université de Lorraine', country_id: 18 },
  { id: 243, name: 'International Institute for the Unification of Private Law', country_id: 23 },
  { id: 244, name: 'Università degli Studi di Perugia', country_id: 23 },
  { id: 245, name: 'Universidad Autónoma de San Luis Potosí', country_id: 27 },
  { id: 246, name: 'Universidad Politécnica de Guanajuato', country_id: 27 },
  { id: 247, name: 'Universidad Tecnológica de los Valles Centrales de Oaxaca', country_id: 27 },
  { id: 248, name: 'Universitè de Genève', country_id: 38 },
  { id: 249, name: 'Universität Zürich', country_id: 38 },
  { id: 250, name: 'Fatih Sultan Mehmet Vakif University', country_id: 39 },
  { id: 251, name: 'Universidade Paulista', country_id: 6 },
  { id: 253, name: 'Pädagogische Hochschule Zug', country_id: 38 },
  { id: 254, name: 'Pädagogische Hochschule Kärnten', country_id: 4 },
  { id: 255, name: 'Universidad EAFIT', country_id: 9 },
  { id: 256, name: 'Fundación Universitaria Autónoma de las Américas', country_id: 9 },
  { id: 257, name: 'Universidad de Medellín', country_id: 9 },
  { id: 258, name: 'University of Nebraska at Kearney', country_id: 16 },
  { id: 259, name: 'École Nationale Supérieure des Mines d Albi-Carmaux', country_id: 18 },
  { id: 260, name: 'Universidad Americana', country_id: 30 },
  { id: 261, name: 'Pädagogische Hochschule Weingarten', country_id: 1 },
  { id: 262, name: 'Institut Universitaire de Technologie de Nîmes', country_id: 18 },
  { id: 263, name: 'Hankuk University of Foreign Studies', country_id: 11 },
  { id: 264, name: 'Universidad Politécnica de Tulancingo', country_id: 27 },
  { id: 265, name: 'Tashkent State Dental Institute', country_id: 41 },
  { id: 266, name: 'Universidad Tecnológica Empresarial de Guayaquil', country_id: 14 },
  { id: 267, name: 'Universidad del Atlántico', country_id: 9 },
  { id: 268, name: 'Universidad Peruana Cayetano Heredia', country_id: 31 },
  { id: 269, name: 'Aberystwyth University', country_id: 42 },
  { id: 270, name: 'Heinrich-Heine-Universität Düsseldorf', country_id: 1 },
  { id: 271, name: 'Universidad Tecnológica Nacional - Facultad Regional Delta', country_id: 2 },
  { id: 272, name: 'Instituto Evangélico de Novo Hamburgo', country_id: 6 },
  { id: 273, name: 'Tampere University of Technology', country_id: 17 },
  { id: 274, name: 'Universidad Paraguayo Alemana', country_id: 30 },
  { id: 275, name: 'Peoples Friendship University of Russia', country_id: 34 },
  { id: 276, name: 'Altinbas University', country_id: 39 },
  { id: 277, name: 'East Carolina University', country_id: 16 },
  { id: 278, name: 'Tecnológico de Costa Rica', country_id: 10 },
  { id: 279, name: 'Universidad Nacional de Loja', country_id: 14 },
  { id: 280, name: 'Fundació Salut i Envelliment UAB', country_id: 15 },
  { id: 281, name: 'Universidad del Cono Sur de las Américas', country_id: 30 },
  { id: 282, name: 'Fachhochschule Münster', country_id: 1 },
  { id: 283, name: 'Universidade do Minho', country_id: 32 },
  { id: 284, name: 'Instituto Politécnico de Lisboa', country_id: 32 },
  { id: 285, name: 'Instituto Internacional de Derecho y Sociedad', country_id: 31 },
  { id: 286, name: 'Adtalem Global Education', country_id: 6 },
  { id: 287, name: 'École normale supérieure Paris-Saclay', country_id: 0 },
  { id: 288, name: 'Institut de Recerca de l Hospital de la Santa Creu i Sant Pau', country_id: 15 },
  { id: 289, name: 'Goethe-Universität Frankfurt', country_id: 1 },
  { id: 290, name: 'Institut National des Sciences Appliquées de Toulouse', country_id: 18 },
  { id: 291, name: 'Instituto Politécnico de Portalegre', country_id: 32 },
  { id: 292, name: 'Instituto Tecnológico de Costa Rica', country_id: 10 },
  { id: 293, name: 'Kanagawa University', country_id: 25 },
  { id: 294, name: 'Leibniz-Universität Hannover', country_id: 1 },
  { id: 295, name: 'Pontificia Universidad Católica do Rio Grande Do Sul', country_id: 6 },
  { id: 296, name: 'PRÓ- SAÚDE Associação Beneficente de Assistência Social e Hospitalar', country_id: 6 },
  { id: 297, name: 'Universidad Antonio Nariño', country_id: 9 },
  { id: 298, name: 'Universidad Autónoma de Guadalajara', country_id: 27 },
  { id: 299, name: 'Universidad Autónoma Metropolitana Unidad Xochimilco', country_id: 27 },
  { id: 300, name: 'Universidad de Cantabria', country_id: 15 },
  { id: 301, name: 'Universidade de Evora', country_id: 32 },
  { id: 302, name: 'Universidad de Sonora', country_id: 27 },
  { id: 303, name: 'University of North Texas', country_id: 16 },
  { id: 304, name: 'Universidad Iberoamericana del Paraguay', country_id: 30 },
  { id: 305, name: 'Universidad Industrial de Santander', country_id: 9 },
  { id: 306, name: 'Universidad Nacional del Rosario', country_id: 27 },
  { id: 307, name: 'Universidad Pontificia Bolivariana', country_id: 9 },
  { id: 308, name: 'Universidad Rey Juan Carlos de España', country_id: 15 },
  { id: 309, name: 'Universität Bremen', country_id: 1 },
  { id: 310, name: 'Université Paris-Diderot', country_id: 18 },
  { id: 311, name: 'Rijksuniversiteit Groningen', country_id: 20 },
  { id: 312, name: 'University of Lakehead', country_id: 7 },
  { id: 313, name: 'University of Sussex', country_id: 21 },
  { id: 314, name: 'Warsaw School of Economics', country_id: 43 },
  { id: 315, name: 'Westfälische Wilhelms-Universität Münster', country_id: 1 },
  { id: 316, name: 'Institut Agro Rennes-Angers', country_id: 18 },
  { id: 317, name: 'Institut Universitaire de Technologie Saint-Étienne', country_id: 18 },
  { id: 318, name: 'Universidad de Talca', country_id: 44 }
]

programs = [
  { id: 1, name: 'Programa 1', description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quas natus exercitationem, adipisci aliquid quibusdam quae veniam unde necessitatibus iusto, earum, harum accusantium itaque nemo saepe repudiandae dignissimos laborum beatae. Assumenda.'},
  { id: 2, name: 'Programa 2', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem perspiciatis sunt ea tempore qui labore iste consectetur, ipsum dicta, ab vero nesciunt recusandae, non hic inventore reiciendis atque placeat dolorem?'},
  { id: 3, name: 'Programa 3', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos tempore voluptatum perferendis expedita dolorem aut ut suscipit quisquam iure in est quasi, corrupti itaque aperiam recusandae? Ea eligendi quidem ratione.'}
]

announcements = [
  { name: 'Convocatoria 1', f_inicio: Date.new(2023, 1, 1), f_fin: Date.new(2023, 3, 1), min_creditos_sct: 150, max_creditos_sct: 85, ramos_reprobados: 3, program_id: 1},
  { name: 'Convocatoria 2', f_inicio: Date.new(2023, 3, 1), f_fin: Date.new(2023, 6, 1), min_creditos_sct: 150, max_creditos_sct: 85, ramos_reprobados: 3, program_id: 1}
]

Announcement.create(announcements)
Program.create(programs)
Language.create(languages)
Country.create(countries)
College.create(colleges)

# Creación de usuario Administrador y usuario simple/postulante

Admin.create!(
  email: 'topher@gmail.com',
  password: 'darktoper98',
  password_confirmation: 'darktoper98'
)

Career.create!(
  name: 'Ingeniería en Informática Empresarial',
  credits: 300,
  college_id: 318
)

User.create!(
  email: 'topherpl98@gmail.com',
  password: 'darktoper98',
  password_confirmation: 'darktoper98',
  rut: '19.718.582-1',
  name: 'Christopher Andrés Paredes López',
  enrollment: '2016419076',
  d_born: Date.new(1998, 1, 2),
  regular_student: true,
  credits_approved: '200',
  failed_subjects: '3',
  has_debts: false,
  has_intern_debts: false,
  career_id: 1
)